name: Rust Tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: cargo test --verbose
      working-directory: ./src/memoir_logger/src/
